### ISSUE TITLE
Does not open in selected folder

### ISSUE THREAD

**Issue by KorbsStudio** [realmazharhussain/nautilus-code#13]
### What happened?

In GNOME Files 43.2, clicking "Open in VSCodium" does not open open the selected folder.

[Screencast from 2023-02-13 12-37-03.webm](https://user-images.githubusercontent.com/51213244/218532086-f2f6d02c-0f04-4bd9-96e1-1211a8996cdf.webm)

### Expected behavior

Open selected folder and editor of choice.

### To Reproduce

1. Open GNOME Files
2. Right-click on a folder
3. Select "Open in (Editor of your choice)"

### Extension Version

v0.5

### Source

RPM Fusion (Official GitHub Repo)

### Environment

- OS: Fedora Workstation 37
- DE: GNOME 43

**Comment by realmazharhussain** [comment]
Is VSCodium installed as a Flatpak?

**Comment by KorbsStudio** [comment]
As already shown in the issue, I've installed it with their RPM file.

**Comment by realmazharhussain** [comment]
And you can run `vscodium /path/to/folder` command on the terminal to open desired folder in VSCodium?

**Comment by KorbsStudio** [comment]
Running a `codium /path/to/folder` command does seem to work as intended.

**Comment by realmazharhussain** [comment]
Make sure nothing important is open in a Nautilus window and then

1. Run the following commands in a terminal

   ```bash
   nautilus -q
   nautilus
   ```
1. Right click on a folder and click on 'Open in VSCodium'

And post the terminal output here.

**Comment by KorbsStudio** [comment]
```bash
[korbs@laptop nautilus-code]$ nautilus -q
** Message: 13:16:55.001: Connecting to org.freedesktop.Tracker3.Miner.Files
Traceback (most recent call last):
  File "/home/korbs/.local/share/nautilus-python/extensions/vscode-nautilus.py", line 21, in <module>
    require_version('Nautilus', '3.0')
  File "/usr/lib64/python3.11/site-packages/gi/__init__.py", line 117, in require_version
    raise ValueError('Namespace %s is already loaded with version %s' %
ValueError: Namespace Nautilus is already loaded with version 4.0


[korbs@laptop nautilus-code]$ nautilus
** Message: 13:17:00.446: Connecting to org.freedesktop.Tracker3.Miner.Files
Traceback (most recent call last):
  File "/home/korbs/.local/share/nautilus-python/extensions/vscode-nautilus.py", line 21, in <module>
    require_version('Nautilus', '3.0')
  File "/usr/lib64/python3.11/site-packages/gi/__init__.py", line 117, in require_version
    raise ValueError('Namespace %s is already loaded with version %s' %
ValueError: Namespace Nautilus is already loaded with version 4.0

(org.gnome.Nautilus:170494): Gtk-WARNING **: 13:17:15.904: Broken accounting of 
active state for widget
```

**Comment by realmazharhussain** [comment]
What is the output of the following command?

```bash
ls /usr/lib/nautilus/extensions-4/ {$HOME/.local,/usr}/share/nautilus-python/extensions/
```

**Comment by KorbsStudio** [comment]
```bash
[korbs@laptop ~]$ sudo ls /usr/lib/nautilus/extensions-4/ /home/korbs/.local/share/nautilus-python/extensions/
ls: cannot access '/usr/lib/nautilus/extensions-4/': No such file or directory
/home/korbs/.local/share/nautilus-python/extensions/:
NautilusCode  nautilus-code.py	__pycache__  vscode-nautilus.py
```

The path `/home/korbs/.local/share/nautilus-python/extensions/` does exist.

The path `/usr/lib/nautilus/extensions-4/` does not exist.

**Comment by realmazharhussain** [comment]
First of all, you need to delete `~/.local/share/nautilus-python/extensions/vscode-nautilus.py`. That extension seems to not support Nautilus 43.

2nd,
- Download [this patch](https://github.com/realmazharhussain/nautilus-code/files/10756631/type.py.patch.txt)
- Run the command

  ```bash
  patch ~/.local/share/nautilus-python/extensions/NautilusCode/types.py type.py.patch.txt
  ```

And then follow the instructions in [this comment](https://github.com/realmazharhussain/nautilus-code/issues/13#issuecomment-1428469305) (again).
